---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook
  namespace: default
  labels:
    app: jupyter-notebook
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 8888
    nodePort: 30001
  selector:
    app: jupyter
---
apiVersion: v1
kind: Pod
metadata:
  name: jupyter
  namespace: default
  labels:
    app: jupyter
spec:
  securityContext:
    fsGroup: 0
  containers:
  - name: jupyter
    #image: tensorflow/tensorflow:latest-gpu-jupyter
    image: quay.io/jupyter/tensorflow-notebook:cuda-latest
    resources:
      limits:
        nvidia.com/gpu: 1 
    ports:
    - containerPort: 8888
      name: notebook
