---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/delayed-ha-bootstrap: ""
    openshift.io/node-selector: ""
    openshift.io/sa.scc.mcs: s0:c8,c2
    openshift.io/sa.scc.supplemental-groups: 1000060000/10000
    openshift.io/sa.scc.uid-range: 1000060000/10000
    workload.openshift.io/allowed: management
  creationTimestamp: "2024-08-04T23:53:59Z"
  labels:
    kubernetes.io/metadata.name: openshift-etcd
    openshift.io/run-level: "0"
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:openshift.io/delayed-ha-bootstrap: {}
          f:openshift.io/node-selector: {}
        f:labels:
          .: {}
          f:kubernetes.io/metadata.name: {}
          f:openshift.io/run-level: {}
    manager: cluster-bootstrap
    operation: Update
    time: "2024-08-04T23:53:59Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:openshift.io/sa.scc.mcs: {}
          f:openshift.io/sa.scc.supplemental-groups: {}
          f:openshift.io/sa.scc.uid-range: {}
    manager: cluster-policy-controller
    operation: Update
    time: "2024-08-04T23:54:08Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:workload.openshift.io/allowed: {}
        f:labels:
          f:pod-security.kubernetes.io/audit: {}
          f:pod-security.kubernetes.io/enforce: {}
          f:pod-security.kubernetes.io/warn: {}
    manager: cluster-etcd-operator
    operation: Update
    time: "2024-08-05T00:23:37Z"
  name: openshift-etcd
  resourceVersion: "8797"
  uid: 5395bf01-a348-4e40-9e8c-eb4bdc696a51
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
