---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    openshift.io/node-selector: ""
    openshift.io/sa.scc.mcs: s0:c23,c2
    openshift.io/sa.scc.supplemental-groups: 1000510000/10000
    openshift.io/sa.scc.uid-range: 1000510000/10000
  creationTimestamp: "2024-08-04T23:55:08Z"
  labels:
    kubernetes.io/metadata.name: openshift-config
    openshift.io/run-level: "0"
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:openshift.io/sa.scc.mcs: {}
          f:openshift.io/sa.scc.supplemental-groups: {}
          f:openshift.io/sa.scc.uid-range: {}
    manager: cluster-policy-controller
    operation: Update
    time: "2024-08-04T23:55:08Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:include.release.openshift.io/hypershift: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
          f:openshift.io/node-selector: {}
        f:labels:
          .: {}
          f:kubernetes.io/metadata.name: {}
          f:openshift.io/run-level: {}
          f:pod-security.kubernetes.io/audit: {}
          f:pod-security.kubernetes.io/enforce: {}
          f:pod-security.kubernetes.io/warn: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"d54a9571-581d-40c9-9074-5da5c8c1b816"}: {}
    manager: cluster-version-operator
    operation: Update
    time: "2024-08-04T23:55:08Z"
  name: openshift-config
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: d54a9571-581d-40c9-9074-5da5c8c1b816
  resourceVersion: "1800"
  uid: 9a4cde02-136f-4874-887a-d28909e95083
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
