apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  # Customise the name to describe the network interface being disabled
  name: okd-configure-master-disable-unused-network-interface
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            # See notes below on generating base64
            source: data:text/plain;charset=utf-8;base64,W21haW5dCnBsdWdpbnM9a2V5ZmlsZQoKW2tleWZpbGVdCnVubWFuYWdlZC1kZXZpY2VzPWludGVyZmFjZS1uYW1lOmVubzIsaW50ZXJmYWNlLW5hbWU6ZW5vMyxpbnRlcmZhY2UtbmFtZTplbm80Cg==
          mode: 420
          # Customise the name to describe the network interface being disabled
          path: /etc/NetworkManager/conf.d/50-disable-unused-interfaces.conf
