apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "packer-windows-2022"
  namespace: default
spec:
  storage:
    storageClassName: ocs-storagecluster-ceph-rbd-virtualization
    resources:
      requests:
        storage: 60Gi
  source:
    http:
      url: "http://192.168.0.5/packer-win2022"
