---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.130.0.13/23"],"mac_address":"0a:58:0a:82:00:0d","gateway_ips":["10.130.0.1"],"routes":[{"dest":"10.128.0.0/14","nextHop":"10.130.0.1"},{"dest":"172.30.0.0/16","nextHop":"10.130.0.1"},{"dest":"100.64.0.0/16","nextHop":"10.130.0.1"}],"ip_address":"10.130.0.13/23","gateway_ip":"10.130.0.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.130.0.13"
          ],
          "mac": "0a:58:0a:82:00:0d",
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-08-05T13:46:53Z"
  labels:
    app: installer
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"b4ead0a8-3b9b-45c6-8276-3168396be223"}: {}
      f:spec:
        f:automountServiceAccountToken: {}
        f:containers:
          k:{"name":"installer"}:
            .: {}
            f:args: {}
            f:command: {}
            f:env:
              .: {}
              k:{"name":"NODE_NAME"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef: {}
              k:{"name":"POD_NAME"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:securityContext:
              .: {}
              f:privileged: {}
              f:runAsUser: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/etc/kubernetes/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/lock"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:readOnly: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:nodeName: {}
        f:priorityClassName: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext:
          .: {}
          f:runAsUser: {}
        f:serviceAccount: {}
        f:serviceAccountName: {}
        f:terminationGracePeriodSeconds: {}
        f:tolerations: {}
        f:volumes:
          .: {}
          k:{"name":"kube-api-access"}:
            .: {}
            f:name: {}
            f:projected:
              .: {}
              f:defaultMode: {}
              f:sources: {}
          k:{"name":"kubelet-dir"}:
            .: {}
            f:hostPath:
              .: {}
              f:path: {}
              f:type: {}
            f:name: {}
          k:{"name":"var-lock"}:
            .: {}
            f:hostPath:
              .: {}
              f:path: {}
              f:type: {}
            f:name: {}
    manager: cluster-etcd-operator
    operation: Update
    time: "2024-08-05T13:46:53Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:k8s.ovn.org/pod-networks: {}
    manager: host3
    operation: Update
    subresource: status
    time: "2024-08-05T13:47:39Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:k8s.v1.cni.cncf.io/network-status: {}
    manager: multus-daemon
    operation: Update
    subresource: status
    time: "2024-08-05T13:48:05Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .: {}
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"PodReadyToStartContainers"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"PodScheduled"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:hostIPs: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.130.0.13"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    subresource: status
    time: "2024-08-05T13:48:50Z"
  name: installer-7-host3
  namespace: openshift-etcd
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: revision-status-7
    uid: b4ead0a8-3b9b-45c6-8276-3168396be223
  resourceVersion: "400446"
  uid: 76fef092-9e96-494c-ada5-9a3c32925a1d
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    - -v=2
    - --revision=7
    - --namespace=openshift-etcd
    - --pod=etcd-pod
    - --resource-dir=/etc/kubernetes/static-pod-resources
    - --pod-manifest-dir=/etc/kubernetes/manifests
    - --configmaps=etcd-pod
    - --configmaps=etcd-serving-ca
    - --configmaps=etcd-peer-client-ca
    - --configmaps=etcd-metrics-proxy-serving-ca
    - --configmaps=etcd-metrics-proxy-client-ca
    - --configmaps=etcd-endpoints
    - --secrets=etcd-all-certs
    - --cert-dir=/etc/kubernetes/static-pod-resources/etcd-certs
    - --cert-configmaps=restore-etcd-pod
    - --cert-configmaps=etcd-scripts
    - --cert-configmaps=etcd-serving-ca
    - --cert-configmaps=etcd-peer-client-ca
    - --cert-configmaps=etcd-metrics-proxy-serving-ca
    - --cert-configmaps=etcd-metrics-proxy-client-ca
    - --cert-secrets=etcd-all-certs
    command:
    - cluster-etcd-operator
    - installer
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f3e57334c06585ab1d45c46da3f7f911c8cf60cb082de43bf7c7d8917bcf07a2
    imagePullPolicy: IfNotPresent
    name: installer
    resources:
      limits:
        cpu: 150m
        memory: 200M
      requests:
        cpu: 150m
        memory: 200M
    securityContext:
      privileged: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /etc/kubernetes/
      name: kubelet-dir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access
      readOnly: true
    - mountPath: /var/lock
      name: var-lock
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: host3
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    runAsUser: 0
  serviceAccount: installer-sa
  serviceAccountName: installer-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes/
      type: ""
    name: kubelet-dir
  - hostPath:
      path: /var/lock
      type: ""
    name: var-lock
  - name: kube-api-access
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3600
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-08-05T13:48:50Z"
    status: "False"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-08-05T13:47:00Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-08-05T13:48:48Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-08-05T13:48:48Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-08-05T13:47:00Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://2e7a232d1ffeb4b71973d5378e5afc36eb0ac1e5f5219db5b3dceec40c373867
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f3e57334c06585ab1d45c46da3f7f911c8cf60cb082de43bf7c7d8917bcf07a2
    imageID: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f3e57334c06585ab1d45c46da3f7f911c8cf60cb082de43bf7c7d8917bcf07a2
    lastState: {}
    name: installer
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://2e7a232d1ffeb4b71973d5378e5afc36eb0ac1e5f5219db5b3dceec40c373867
        exitCode: 0
        finishedAt: "2024-08-05T13:48:48Z"
        reason: Completed
        startedAt: "2024-08-05T13:48:16Z"
  hostIP: 192.168.0.251
  hostIPs:
  - ip: 192.168.0.251
  phase: Succeeded
  podIP: 10.130.0.13
  podIPs:
  - ip: 10.130.0.13
  qosClass: Guaranteed
  startTime: "2024-08-05T13:47:00Z"
