---
apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2024-08-23T15:18:19Z"
    creationTimestamp: "2024-08-04T23:54:32Z"
    labels:
      k8s-app: etcd
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:k8s-app: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-23T15:18:55Z"
    name: etcd
    namespace: openshift-etcd
    resourceVersion: "41891395"
    uid: 2f1bda35-fe9c-4bd3-9571-025e83185a63
  subsets:
  - addresses:
    - ip: 192.168.0.249
      nodeName: host1
      targetRef:
        kind: Pod
        name: etcd-host1
        namespace: openshift-etcd
        uid: 44f2ef74-703a-44bb-b08b-a5481d281abd
    - ip: 192.168.0.251
      nodeName: host3
      targetRef:
        kind: Pod
        name: etcd-host3
        namespace: openshift-etcd
        uid: d61190af-5457-4902-90e0-8e3fb7a69927
    notReadyAddresses:
    - ip: 192.168.0.250
      nodeName: host2
      targetRef:
        kind: Pod
        name: etcd-host2
        namespace: openshift-etcd
        uid: 1989232a-9cec-420d-a1c1-09cf8815cab1
    ports:
    - name: etcd
      port: 2379
      protocol: TCP
    - name: etcd-metrics
      port: 9979
      protocol: TCP
kind: EndpointsList
metadata:
  resourceVersion: "42198335"
