---
apiVersion: discovery.k8s.io/v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.130.0.69
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: host3
    targetRef:
      kind: Pod
      name: etcd-operator-75956966d5-924bk
      namespace: openshift-etcd-operator
      uid: 336c96fd-4e08-45b3-aecd-960ecabe53dd
  kind: EndpointSlice
  metadata:
    creationTimestamp: "2024-08-04T23:54:49Z"
    generateName: metrics-
    generation: 221
    labels:
      app: etcd-operator
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: metrics
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:kubernetes.io/service-name: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"7557a68d-0826-4a2d-b6eb-6d99956380e5"}: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-22T00:12:02Z"
    name: metrics-q7pnb
    namespace: openshift-etcd-operator
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: metrics
      uid: 7557a68d-0826-4a2d-b6eb-6d99956380e5
    resourceVersion: "35977849"
    uid: 0319e225-5bd7-4fe5-81ff-20803b60103a
  ports:
  - name: https
    port: 8443
    protocol: TCP
kind: EndpointSliceList
metadata:
  resourceVersion: "42198225"
