---
apiVersion: config.openshift.io/v1
items:
- apiVersion: config.openshift.io/v1
  kind: APIServer
  metadata:
    annotations:
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      oauth-apiserver.openshift.io/secure-token-storage: "true"
      release.openshift.io/create-only: "true"
    creationTimestamp: "2024-08-04T23:54:48Z"
    generation: 1
    managedFields:
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:include.release.openshift.io/ibm-cloud-managed: {}
            f:include.release.openshift.io/self-managed-high-availability: {}
            f:oauth-apiserver.openshift.io/secure-token-storage: {}
            f:release.openshift.io/create-only: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"d54a9571-581d-40c9-9074-5da5c8c1b816"}: {}
        f:spec:
          .: {}
          f:audit:
            .: {}
            f:profile: {}
      manager: cluster-version-operator
      operation: Update
      time: "2024-08-04T23:54:48Z"
    name: cluster
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: d54a9571-581d-40c9-9074-5da5c8c1b816
    resourceVersion: "994"
    uid: 8042125f-b401-436e-9392-ba08e97bf1d8
  spec:
    audit:
      profile: Default
kind: APIServerList
metadata:
  continue: ""
  resourceVersion: "42198067"
