apiVersion: config.openshift.io/v1
items:
- apiVersion: config.openshift.io/v1
  kind: Authentication
  metadata:
    annotations:
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      release.openshift.io/create-only: "true"
    creationTimestamp: "2024-08-04T23:54:53Z"
    generation: 2
    managedFields:
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:include.release.openshift.io/ibm-cloud-managed: {}
            f:include.release.openshift.io/self-managed-high-availability: {}
            f:release.openshift.io/create-only: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"d54a9571-581d-40c9-9074-5da5c8c1b816"}: {}
        f:spec: {}
      manager: cluster-version-operator
      operation: Update
      time: "2024-08-04T23:54:53Z"
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:oauthMetadata:
            .: {}
            f:name: {}
          f:serviceAccountIssuer: {}
          f:type: {}
          f:webhookTokenAuthenticator:
            .: {}
            f:kubeConfig:
              .: {}
              f:name: {}
      manager: authentication-operator
      operation: Update
      time: "2024-08-05T00:24:57Z"
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:integratedOAuthMetadata:
            .: {}
            f:name: {}
      manager: authentication-operator
      operation: Update
      subresource: status
      time: "2024-08-05T00:47:23Z"
    name: cluster
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: d54a9571-581d-40c9-9074-5da5c8c1b816
    resourceVersion: "24620"
    uid: 2510666e-ddc9-4e5b-ae46-c3d925c01036
  spec:
    oauthMetadata:
      name: ""
    serviceAccountIssuer: ""
    type: ""
    webhookTokenAuthenticator:
      kubeConfig:
        name: webhook-authentication-integrated-oauth
  status:
    integratedOAuthMetadata:
      name: oauth-openshift
kind: AuthenticationList
metadata:
  continue: ""
  resourceVersion: "42198064"
