---
apiVersion: config.openshift.io/v1
items:
- apiVersion: config.openshift.io/v1
  kind: Build
  metadata:
    annotations:
      capability.openshift.io/name: Build
      include.release.openshift.io/hypershift: "true"
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      include.release.openshift.io/single-node-developer: "true"
      release.openshift.io/create-only: "true"
    creationTimestamp: "2024-08-04T23:54:48Z"
    generation: 1
    managedFields:
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:capability.openshift.io/name: {}
            f:include.release.openshift.io/hypershift: {}
            f:include.release.openshift.io/ibm-cloud-managed: {}
            f:include.release.openshift.io/self-managed-high-availability: {}
            f:include.release.openshift.io/single-node-developer: {}
            f:release.openshift.io/create-only: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"d54a9571-581d-40c9-9074-5da5c8c1b816"}: {}
        f:spec: {}
      manager: cluster-version-operator
      operation: Update
      time: "2024-08-04T23:54:48Z"
    name: cluster
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: d54a9571-581d-40c9-9074-5da5c8c1b816
    resourceVersion: "985"
    uid: b39dc531-f5e8-4fa5-8987-0d5c8c9c1eb0
  spec: {}
kind: BuildList
metadata:
  continue: ""
  resourceVersion: "42198064"
