---
apiVersion: config.openshift.io/v1
items:
- apiVersion: config.openshift.io/v1
  kind: ClusterVersion
  metadata:
    creationTimestamp: "2024-08-04T23:54:21Z"
    generation: 2
    managedFields:
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:channel: {}
          f:clusterID: {}
      manager: cluster-bootstrap
      operation: Update
      time: "2024-08-04T23:54:21Z"
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:availableUpdates: {}
          f:capabilities:
            .: {}
            f:enabledCapabilities: {}
            f:knownCapabilities: {}
          f:conditionalUpdates: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Failing"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"ImplicitlyEnabledCapabilities"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"ReleaseAccepted"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"RetrievedUpdates"}:
              .: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
          f:desired:
            .: {}
            f:channels:
              .: {}
              v:"candidate-4.16": {}
              v:"candidate-4.17": {}
              v:"eus-4.16": {}
              v:"fast-4.16": {}
              v:"stable-4.16": {}
            f:image: {}
            f:url: {}
            f:version: {}
          f:history: {}
          f:observedGeneration: {}
          f:versionHash: {}
      manager: cluster-version-operator
      operation: Update
      subresource: status
      time: "2024-08-23T16:35:19Z"
    name: version
    resourceVersion: "42072185"
    uid: d54a9571-581d-40c9-9074-5da5c8c1b816
  spec:
    channel: stable-4.16
    clusterID: 1cb49724-6a9b-4419-aaf6-b8a4a335ea6b
  status:
    availableUpdates:
    - channels:
      - candidate-4.16
      - candidate-4.17
      - eus-4.16
      - fast-4.16
      - stable-4.16
      image: quay.io/openshift-release-dev/ocp-release@sha256:0d365611e78c5306975753975419851183536354273a6340021f9b1cdd2a34c3
      url: https://access.redhat.com/errata/RHSA-2024:5107
      version: 4.16.7
    - channels:
      - candidate-4.16
      - candidate-4.17
      - eus-4.16
      - fast-4.16
      - stable-4.16
      image: quay.io/openshift-release-dev/ocp-release@sha256:24ea553ce2e79fab0ff9cf2917d26433cffb3da954583921926034b9d5d309bd
      url: https://access.redhat.com/errata/RHSA-2024:4965
      version: 4.16.6
    - channels:
      - candidate-4.16
      - candidate-4.17
      - eus-4.16
      - fast-4.16
      - stable-4.16
      image: quay.io/openshift-release-dev/ocp-release@sha256:ac78ebf77f95ab8ff52847ecd22592b545415e1ff6c7ff7f66bf81f158ae4f5e
      url: https://access.redhat.com/errata/RHBA-2024:4855
      version: 4.16.5
    capabilities:
      enabledCapabilities:
      - Build
      - CSISnapshot
      - CloudControllerManager
      - CloudCredential
      - Console
      - DeploymentConfig
      - ImageRegistry
      - Ingress
      - Insights
      - MachineAPI
      - NodeTuning
      - OperatorLifecycleManager
      - Storage
      - baremetal
      - marketplace
      - openshift-samples
      knownCapabilities:
      - Build
      - CSISnapshot
      - CloudControllerManager
      - CloudCredential
      - Console
      - DeploymentConfig
      - ImageRegistry
      - Ingress
      - Insights
      - MachineAPI
      - NodeTuning
      - OperatorLifecycleManager
      - Storage
      - baremetal
      - marketplace
      - openshift-samples
    conditionalUpdates:
    - conditions:
      - lastTransitionTime: "2024-08-23T16:35:19Z"
        message: The update is recommended, because none of the conditional update
          risks apply to this cluster.
        reason: NotExposedToRisks
        status: "True"
        type: Recommended
      release:
        channels:
        - candidate-4.16
        - candidate-4.17
        - eus-4.16
        - fast-4.16
        - stable-4.16
        image: quay.io/openshift-release-dev/ocp-release@sha256:0d365611e78c5306975753975419851183536354273a6340021f9b1cdd2a34c3
        url: https://access.redhat.com/errata/RHSA-2024:5107
        version: 4.16.7
      risks:
      - matchingRules:
        - promql:
            promql: |
              group(csv_succeeded{_id="", name=~"sriov-network-operator[.].*"})
              or
              0 * group(csv_count{_id=""})
          type: PromQL
        message: On clusters with the SR-IOV Network Operator installed and configured,
          pods with a secondary interface of SRI-OV VF will fail to create a pod sandbox
          and thus will not function.
        name: SRIOVFailedToConfigureVF
        url: https://issues.redhat.com/browse/NHE-1171
    conditions:
    - lastTransitionTime: "2024-08-23T16:35:19Z"
      status: "True"
      type: RetrievedUpdates
    - lastTransitionTime: "2024-08-04T23:54:44Z"
      message: Capabilities match configured spec
      reason: AsExpected
      status: "False"
      type: ImplicitlyEnabledCapabilities
    - lastTransitionTime: "2024-08-04T23:54:44Z"
      message: Payload loaded version="4.16.4" image="quay.io/openshift-release-dev/ocp-release@sha256:633d1d36e834a70baf666994ef375b9d1702bd1c54ab46f96c41223af9c2d150"
        architecture="amd64"
      reason: PayloadLoaded
      status: "True"
      type: ReleaseAccepted
    - lastTransitionTime: "2024-08-21T21:16:58Z"
      status: "False"
      type: Available
    - lastTransitionTime: "2024-08-23T15:21:57Z"
      message: Cluster operator etcd is degraded
      reason: ClusterOperatorDegraded
      status: "True"
      type: Failing
    - lastTransitionTime: "2024-08-05T13:49:32Z"
      message: 'Error while reconciling 4.16.4: the cluster operator etcd is degraded'
      reason: ClusterOperatorDegraded
      status: "False"
      type: Progressing
    desired:
      channels:
      - candidate-4.16
      - candidate-4.17
      - eus-4.16
      - fast-4.16
      - stable-4.16
      image: quay.io/openshift-release-dev/ocp-release@sha256:633d1d36e834a70baf666994ef375b9d1702bd1c54ab46f96c41223af9c2d150
      url: https://access.redhat.com/errata/RHSA-2024:4613
      version: 4.16.4
    history:
    - completionTime: "2024-08-05T13:49:32Z"
      image: quay.io/openshift-release-dev/ocp-release@sha256:633d1d36e834a70baf666994ef375b9d1702bd1c54ab46f96c41223af9c2d150
      startedTime: "2024-08-04T23:54:44Z"
      state: Completed
      verified: false
      version: 4.16.4
    observedGeneration: 2
    versionHash: ybt5SS-NLak=
kind: ClusterVersionList
metadata:
  continue: ""
  resourceVersion: "42198066"
