---
apiVersion: config.openshift.io/v1
items:
- apiVersion: config.openshift.io/v1
  kind: Network
  metadata:
    creationTimestamp: "2024-08-04T23:54:17Z"
    generation: 17
    managedFields:
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:clusterNetwork: {}
          f:externalIP:
            f:policy: {}
          f:networkType: {}
          f:serviceNetwork: {}
        f:status:
          f:clusterNetwork: {}
          f:clusterNetworkMTU: {}
          f:networkType: {}
          f:serviceNetwork: {}
      manager: cluster-network-operator/operconfig
      operation: Apply
      time: "2024-08-05T00:04:39Z"
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            k:{"type":"NetworkDiagnosticsAvailable"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
      manager: cluster-network-operator/connectivity-check-controller
      operation: Apply
      time: "2024-08-23T02:26:36Z"
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:clusterNetwork: {}
          f:externalIP:
            .: {}
            f:policy: {}
          f:networkDiagnostics:
            .: {}
            f:mode: {}
            f:sourcePlacement: {}
            f:targetPlacement: {}
          f:networkType: {}
          f:serviceNetwork: {}
        f:status: {}
      manager: cluster-bootstrap
      operation: Update
      time: "2024-08-04T23:54:17Z"
    name: cluster
    resourceVersion: "39950107"
    uid: 25087af5-2be5-4911-94c0-8fcd4d79d5f2
  spec:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    externalIP:
      policy: {}
    networkDiagnostics:
      mode: ""
      sourcePlacement: {}
      targetPlacement: {}
    networkType: OVNKubernetes
    serviceNetwork:
    - 172.30.0.0/16
  status:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    clusterNetworkMTU: 1400
    conditions:
    - lastTransitionTime: "2024-08-23T02:26:36Z"
      message: ""
      reason: AsExpected
      status: "True"
      type: NetworkDiagnosticsAvailable
    networkType: OVNKubernetes
    serviceNetwork:
    - 172.30.0.0/16
kind: NetworkList
metadata:
  continue: ""
  resourceVersion: "42198069"
