---
apiVersion: config.openshift.io/v1
items:
- apiVersion: config.openshift.io/v1
  kind: OperatorHub
  metadata:
    annotations:
      capability.openshift.io/name: marketplace
      include.release.openshift.io/hypershift: "true"
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      include.release.openshift.io/single-node-developer: "true"
      release.openshift.io/create-only: "true"
    creationTimestamp: "2024-08-04T23:54:48Z"
    generation: 1
    managedFields:
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:capability.openshift.io/name: {}
            f:include.release.openshift.io/hypershift: {}
            f:include.release.openshift.io/ibm-cloud-managed: {}
            f:include.release.openshift.io/self-managed-high-availability: {}
            f:include.release.openshift.io/single-node-developer: {}
            f:release.openshift.io/create-only: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"d54a9571-581d-40c9-9074-5da5c8c1b816"}: {}
        f:spec: {}
      manager: cluster-version-operator
      operation: Update
      time: "2024-08-04T23:54:48Z"
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:sources: {}
      manager: marketplace-operator
      operation: Update
      subresource: status
      time: "2024-08-23T12:27:06Z"
    name: cluster
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: d54a9571-581d-40c9-9074-5da5c8c1b816
    resourceVersion: "41461427"
    uid: 287621f4-54aa-4235-b6f6-91a385a06e48
  spec: {}
  status:
    sources:
    - disabled: false
      name: redhat-operators
      status: Success
    - disabled: false
      name: certified-operators
      status: Success
    - disabled: false
      name: community-operators
      status: Success
    - disabled: false
      name: redhat-marketplace
      status: Success
kind: OperatorHubList
metadata:
  continue: ""
  resourceVersion: "42198066"
