---
apiVersion: config.openshift.io/v1
items:
- apiVersion: config.openshift.io/v1
  kind: Project
  metadata:
    annotations:
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      release.openshift.io/create-only: "true"
    creationTimestamp: "2024-08-04T23:55:05Z"
    generation: 1
    managedFields:
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:include.release.openshift.io/ibm-cloud-managed: {}
            f:include.release.openshift.io/self-managed-high-availability: {}
            f:release.openshift.io/create-only: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"d54a9571-581d-40c9-9074-5da5c8c1b816"}: {}
        f:spec: {}
      manager: cluster-version-operator
      operation: Update
      time: "2024-08-04T23:55:05Z"
    name: cluster
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: d54a9571-581d-40c9-9074-5da5c8c1b816
    resourceVersion: "1732"
    uid: 7b3d8bf3-f02f-4f41-a74d-bc6245f09605
  spec: {}
kind: ProjectList
metadata:
  continue: ""
  resourceVersion: "42198067"
