---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    openshift.io/node-selector: ""
    openshift.io/sa.scc.mcs: s0:c22,c19
    openshift.io/sa.scc.supplemental-groups: 1000500000/10000
    openshift.io/sa.scc.uid-range: 1000500000/10000
  creationTimestamp: "2024-08-04T23:55:07Z"
  labels:
    kubernetes.io/metadata.name: openshift-config-managed
    openshift.io/run-level: "0"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:openshift.io/sa.scc.mcs: {}
          f:openshift.io/sa.scc.supplemental-groups: {}
          f:openshift.io/sa.scc.uid-range: {}
    manager: cluster-policy-controller
    operation: Update
    time: "2024-08-04T23:55:07Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:include.release.openshift.io/hypershift: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
          f:openshift.io/node-selector: {}
        f:labels:
          .: {}
          f:kubernetes.io/metadata.name: {}
          f:openshift.io/run-level: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"d54a9571-581d-40c9-9074-5da5c8c1b816"}: {}
    manager: cluster-version-operator
    operation: Update
    time: "2024-08-04T23:55:07Z"
  name: openshift-config-managed
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: d54a9571-581d-40c9-9074-5da5c8c1b816
  resourceVersion: "1781"
  uid: b0486399-c427-4418-8e32-125f968532f9
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
